Traceback (most recent call last):
  File "/Users/joarteaga/Documents/JAAC/Uninorte/Maest Est Aplicada/3c. VISUALIZACIOÃÅN EN R Y PYTHON/Visualizacion_JA_AP/ProyectoFinal_Python/my-book-files/venv_jupyter/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/joarteaga/Documents/JAAC/Uninorte/Maest Est Aplicada/3c. VISUALIZACIOÃÅN EN R Y PYTHON/Visualizacion_JA_AP/ProyectoFinal_Python/my-book-files/venv_jupyter/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/joarteaga/Documents/JAAC/Uninorte/Maest Est Aplicada/3c. VISUALIZACIOÃÅN EN R Y PYTHON/Visualizacion_JA_AP/ProyectoFinal_Python/my-book-files/venv_jupyter/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/joarteaga/Documents/JAAC/Uninorte/Maest Est Aplicada/3c. VISUALIZACIOÃÅN EN R Y PYTHON/Visualizacion_JA_AP/ProyectoFinal_Python/my-book-files/venv_jupyter/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/joarteaga/Documents/JAAC/Uninorte/Maest Est Aplicada/3c. VISUALIZACIOÃÅN EN R Y PYTHON/Visualizacion_JA_AP/ProyectoFinal_Python/my-book-files/venv_jupyter/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/joarteaga/Documents/JAAC/Uninorte/Maest Est Aplicada/3c. VISUALIZACIOÃÅN EN R Y PYTHON/Visualizacion_JA_AP/ProyectoFinal_Python/my-book-files/venv_jupyter/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/joarteaga/Documents/JAAC/Uninorte/Maest Est Aplicada/3c. VISUALIZACIOÃÅN EN R Y PYTHON/Visualizacion_JA_AP/ProyectoFinal_Python/my-book-files/venv_jupyter/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Modulos nativos de Python
from datetime import datetime, timedelta
import pickle
import warnings

#Modulos de visualizaci√≥n
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import seaborn as sns
from plotly.subplots import make_subplots

#Modulos para gestionar dataframes, c√°lculos con vectores y matrices
import numpy  as np
import pandas as pd

#Modulos para las pruebas estad√≠sticas para series de tiempo
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf

#Modulos para la generaci√≥n de modelos
import statsmodels.api as sm
from statsmodels.tsa.arima.model import ARIMA

#Modulos para manejar la base de datos
import psycopg2
from sqlalchemy import create_engine

#Modulos para obtener datos de las acciones actualizadas
import finnhub

warnings.filterwarnings("ignore")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/var/folders/w2/j_r2nxj526x02wjfw52mqty1h_5b0_/T/ipykernel_86871/17236782.py[0m in [0;36m<module>[0;34m[0m
[1;32m     23[0m [0;34m[0m[0m
[1;32m     24[0m [0;31m#Modulos para manejar la base de datos[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 25[0;31m [0;32mimport[0m [0mpsycopg2[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     26[0m [0;32mfrom[0m [0msqlalchemy[0m [0;32mimport[0m [0mcreate_engine[0m[0;34m[0m[0;34m[0m[0m
[1;32m     27[0m [0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'psycopg2'
ModuleNotFoundError: No module named 'psycopg2'

